export const Colors = {
  light: {
    background: '#F3F3F3',
    display: '#000000',
    buttonNumber: '#FFFFFF',
    buttonFunction: '#D4D4D2',
    buttonOperator: '#FF9F0A',
    textNumber: '#000000',
    textFunction: '#000000',
    textOperator: '#FFFFFF',
    buttonPressedNumber: '#E5E5E5',
    buttonPressedFunction: '#BCBCBA',
    buttonPressedOperator: '#CC7F08',
    statusBar: 'dark-content' as const,
  },
  dark: {
    background: '#000000',
    display: '#FFFFFF',
    buttonNumber: '#333333',
    buttonFunction: '#A5A5A5',
    buttonOperator: '#FF9F0A',
    textNumber: '#FFFFFF',
    textFunction: '#000000',
    textOperator: '#FFFFFF',
    buttonPressedNumber: '#737373',
    buttonPressedFunction: '#D9D9D9',
    buttonPressedOperator: '#CC7F08',
    statusBar: 'light-content' as const,
  },
};
